spring:
  application:
    name: markable-dev-analytics
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devanalytics
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

git:
  repositories:
    - https://scm.x5.ru/gkr/xrg-core.git
    - https://scm.x5.ru/gkr/xrg-markable.git
    - https://scm.x5.ru/gkpl/logistics-service.git
    - https://scm.x5.ru/gkpl/pricing-service.git
    - https://scm.x5.ru/gkpl/platform-service.git
    - https://scm.x5.ru/gkpl/bo-oas.git
  token: eWzfJEmRUwLnWRsHWoFuHm86MQp1OjJnCA.01.0y0bfbayt
  cache-directory: /Users/boris.osechinskiy/Documents/git-cache/

ai:
  url: https://api-copilot.x5.ru/aigw/v1
  api-key: fa4b5a32-eeb8-45ce-a74b-850e131d7e56
  model: copilot-code-large
  timeout: 30000

kaiten:
  api:
    url: https://kaiten.x5.ru/api/latest
    token: 940a0f59-83da-4794-9ace-2a0570e51619
    space-ids: 1700

server:
  port: 8080